name: Build Source Code on Windows ðŸªŸ

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  BINARY_NAME: Sandbox

jobs:
  windows-build:
    runs-on: windows-2022

    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Install dependencies
        id: install-deps
        shell: pwsh
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install jinja2

      - name: MSVC Build x64
        id: msvc-build
        shell: pwsh
        run: |
          cmake --preset=ci-windows-x64-msvc -DPython_EXECUTABLE="$((get-command python3).Path)"
          cmake --build --preset=ci-windows-x64-msvc
        
      - name: Create artifact 
        id: create-artifact
        shell: pwsh 
        run: |
          New-Item -ItemType Directory -Path artifact
          Get-ChildItem -Recurse -Include *.exe
          & 7z a ./artifact/${{ env.BINARY_NAME }}-windows-x64.zip ./build/bin/${{ env.BINARY_NAME }}.exe ./build/bin/assets
      
      - name: Upload artifact 
        uses: actions/upload-artifact@v4  
        with:
          name: ${{ env.BINARY_NAME }}-binary-archives
          path: artifact 

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        if: github.event_name != 'pull_request'
        with:
          ref: unstable-latest 

      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        if: github.event_name != 'pull_request'
        with:
          files: ./artifact/${{ env.BINARY_NAME }}-windows-x64.zip
          prerelease: true
          name: Auto Unstable Build
          tag_name: unstable-latest